// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "GameFramework/Actor.h"
#include "CGWeapon.generated.h"

#define WEAPON_TRACE_TAG FName("WeaponTrace")

#pragma region Structs
USTRUCT()
struct FCGWeaponConfig
{
	GENERATED_USTRUCT_BODY()

	UPROPERTY(EditDefaultsOnly, Category = Timing)
	float TimeBetweenShots;

	UPROPERTY(EditDefaultsOnly, Category = Timing)
	uint32 bAutomaticFire : 1;

	UPROPERTY(EditDefaultsOnly, Category = Timing)
	float EquipTime;

	UPROPERTY(EditDefaultsOnly, Category = Timing)
	float UnequipTime;

	UPROPERTY(EditDefaultsOnly, Category = WeaponAttributes)
	uint32 bUsesProjectile : 1;
	
	UPROPERTY(EditDefaultsOnly, Category = WeaponAttributes)
	TSubclassOf<UDamageType> DamageType;
	
	/** The damage caused by a single shot. */
	UPROPERTY(EditDefaultsOnly, Category=WeaponAttributes)
	float BaseDamage;

	/** The range at which the gun can be reliably shot to. In hitscan guns this is the maximu range of the gun.*/
	UPROPERTY(EditDefaultsOnly, Category = WeaponAttributes)
	float WeaponRange;

	UPROPERTY(EditDefaultsOnly, Category = WeaponAttributes)
	uint32 OverHeatWeapon : 1;

	FCGWeaponConfig()
	{
		// Timing.
		TimeBetweenShots = .01;
		bAutomaticFire = false;
		EquipTime   = .05f;
		UnequipTime = .05f;
	
		// Attributes.
		bUsesProjectile = true;
		BaseDamage  = 10.f;
		WeaponRange = 10000.f;

		OverHeatWeapon = false;
	}
};

USTRUCT()
struct FCGAmmoData
{
	GENERATED_USTRUCT_BODY()

	UPROPERTY(EditDefaultsOnly, Category = WeaponAttributes)
	int32 AmmoPerShot;

	UPROPERTY(EditDefaultsOnly, Category = WeaponAttributes)
	int32 AmmoCapacity;

	UPROPERTY(EditDefaultsOnly, Category = WeaponAttributes)
	int32 ClipSize;

	/** The amount of time that the weapon is in the "Reload" state. */
	UPROPERTY(EditDefaultsOnly)
	float ReloadTime;

	FCGAmmoData()
	{
		AmmoPerShot  = 1;
		AmmoCapacity = 100;
		ClipSize     = 10;
		ReloadTime = .5f;
	}
};

USTRUCT()
struct FCGOverheatAmmoData
{
	GENERATED_USTRUCT_BODY()

	/** The maximum "heat" that the pistol can achieve before */
	UPROPERTY(EditDefaultsOnly)
	float MaxHeat;

	/** The heat generated by each shot. */
	UPROPERTY(EditDefaultsOnly)
	float HeatPerShot;

	/** Heat reduction per second.*/
	UPROPERTY(EditDefaultsOnly)
	float CooldownPerSecond;

	UPROPERTY(EditDefaultsOnly)
	float OverheatTime;


	/** Sets defaults */
	FCGOverheatAmmoData()
	{
		// Heat settings.
		MaxHeat = 100.f;
		HeatPerShot = 15.f;
		CooldownPerSecond = 30.f;
		OverheatTime = .5f;
	}
};


USTRUCT()
struct FCGProjectileData
{
	GENERATED_USTRUCT_BODY()

	/** The class of the Projectile that will be shot by the weapon. */
	UPROPERTY(EditDefaultsOnly)
	TSubclassOf<class ACGProjectile> ProjectileClass;

	/** The life span of the projectile before despawning. */
	UPROPERTY(EditDefaultsOnly)
	float ProjectileLife;

	/** Sets defaults */
	FCGProjectileData()
	{
		ProjectileClass = NULL;
		ProjectileLife = 2.0f;
	}
};

USTRUCT()
struct FCGSpreadData
{
	GENERATED_USTRUCT_BODY()	

	/** The angle (in Degrees) of the base spread for this gun.*/
	UPROPERTY(EditDefaultsOnly)
	float BaseSpread;

	/** The angle (in Degrees) of the max spread for this gun.*/
	UPROPERTY(EditDefaultsOnly)
	float MaxSpread;

	/** The angle (in Degrees) that the gun spreads each continuous shot.*/
	UPROPERTY(EditDefaultsOnly)
	float SpreadPerShot;

	FCGSpreadData()
	{
		MaxSpread     = 0.f;
		BaseSpread    = 0.f;
		SpreadPerShot = 0.f;
	}
};

//FIXME this can be done with the seed and spread.
USTRUCT()
struct FCGInstantHit
{
	GENERATED_USTRUCT_BODY()

	UPROPERTY()
	FVector Origin;

	UPROPERTY()
	FVector Direction;
};

/** VFX and SFX related to the weapon.*/
USTRUCT()
struct FCGWeaponFXData
{
	GENERATED_USTRUCT_BODY()

	////////////////////////////
	// VFX

	/** The socket on the gun model that corresponds to the muzzle of the gun. */
	UPROPERTY(EditDefaultsOnly, Category = Effects)
	FName MuzzleSocket;

	/** The Muzzle flash for the gun. */
	UPROPERTY(EditDefaultsOnly, Category = Effects)
	UParticleSystem* MuzzleFlash;

	/** The name of the end of the trail in the material editor, should be in the target property.*/
	UPROPERTY(EditDefaultsOnly, Category = Effects)
	FName TrailTargetParam;

	/** The Weapon trail for the bullet. Typically only used by hit scan weapons. */
	UPROPERTY(EditDefaultsOnly, Category = Effects)
	UParticleSystem* WeaponTrail;

	// TODO Improve impact.
	UPROPERTY(EditDefaultsOnly, Category = Projectile)
	UParticleSystem* ImpactEffect;

	UPROPERTY(EditDefaultsOnly, Category = Effects)
	TSubclassOf<UCameraShake> CameraShake;
	

	////////////////////////////
	// SFX

	// XXX Maybe this should be a sound cue to prevent non prepped sounds from being used?
	/** Played on weapon fire. */
	UPROPERTY(EditDefaultsOnly, Category = Effects)
	class USoundBase* FireSound;

	FCGWeaponFXData()
	{
		/** The default name of the Muzzle socket. */
		MuzzleSocket = TEXT("MuzzleFlashSocket");
		TrailTargetParam = TEXT("TrailEnd");

	}
};

/** HUD Textures and configuration.*/
USTRUCT()
struct FCGWeaponHUDData
{
	GENERATED_USTRUCT_BODY()

	/**The crosshair icon for the weapon. Base color should be white. */
	UPROPERTY(EditDefaultsOnly, Category = HUD)
	FCanvasIcon CrosshairIcon;

	/**The Ammo Guage Background for the weapon. Base color should be white. */
	UPROPERTY(EditDefaultsOnly, Category = HUD)
	FCanvasIcon AmmoGuageBGIcon;

	/**The Ammo Guage Foreground for the weapon. Base color should be white. */
	UPROPERTY(EditDefaultsOnly, Category = HUD)
	FCanvasIcon AmmoGuageFGIcon;

	/**The Weapon Icon for the weapon. Base color should be white. */
	UPROPERTY(EditDefaultsOnly, Category = HUD)
	FCanvasIcon WeaponIcon;

	/** Color for when the player has expended all of their available ammo for a clip.*/
	UPROPERTY(EditDefaultsOnly, Category = HUD)
	FLinearColor  LowAmmoColor;

	/** Color for when the player has expended none of their available ammo for a clip.*/
	UPROPERTY(EditDefaultsOnly, Category = HUD)
	FLinearColor  FullAmmoColor;

	/** The width of the ammo clip in pixels*/
	UPROPERTY(EditDefaultsOnly, Category = HUD)
	float AmmoGuageWidth;

	FCGWeaponHUDData()
	{
		// Default colors for the ammo readout.
		LowAmmoColor = FLinearColor(1, 0, 0, 1); // Red
		FullAmmoColor = FLinearColor(0, 1, 0, 1); // Green

		AmmoGuageWidth = 256.0f;
	}
};

#pragma endregion

/**
 * 
 */
UCLASS( Abstract,  Config=Game)
class CRYSTALLINE_API ACGWeapon : public AActor
{
	GENERATED_BODY()

	// Give the states access to the weapon.
	friend class UCGWeaponState;
	friend class UCGWeaponActiveState;
	friend class UCGWeaponInactiveState;
	friend class UCGWeaponEquippingState;
	friend class UCGWeaponUnequippingState;
	friend class UCGWeaponFiringState;
	friend class UCGWeaponReloadingState;

public:
	ACGWeapon(const FObjectInitializer& ObjectInitializer);
	
	virtual void PostInitializeComponents() override;
	virtual void BeginPlay() override;
	virtual void Tick(float DeltaSeconds) override;


#pragma region Visuals
protected:
	/** weapon mesh: 1st person view */
	UPROPERTY(VisibleDefaultsOnly, Category = Mesh)
	USkeletalMeshComponent* Mesh1P;

#pragma endregion 


public:
	////////////////////////////
	// Config

	/** Generic weapon configuration settings.*/
	UPROPERTY(EditDefaultsOnly, Category = Config)
	FCGWeaponConfig WeaponConfig;

	UPROPERTY(EditDefaultsOnly, Category = Config)
	FCGProjectileData ProjectileConfig;

	UPROPERTY(EditDefaultsOnly, Category = Config)
	FCGSpreadData SpreadConfig;

	/** Generic weapon effect configuration settings.*/
	UPROPERTY(EditDefaultsOnly, Category = Config)
	FCGWeaponFXData WeaponFXConfig;

	/** Generic weapon HUD configuration settings.*/
	UPROPERTY(EditDefaultsOnly, Category = Config)
	FCGWeaponHUDData WeaponHUDConfig;
	
	/**Defines the zoom factor for the weapon.*/
	UPROPERTY(EditDefaultsOnly, Category = Config)
	FCGZoom WeaponZoomConfig;
	

	////////////////////////////
	// Mutable weapon fields

	// Keeps track of the current burst. Ammo Doesn't need to be replicated.
	UPROPERTY(Transient, ReplicatedUsing=OnRep_BurstCount)
	int32 BurstCount;

	/** The time of the last shot by the weapon.*/
	UPROPERTY()
	float LastFireTime;

	UPROPERTY()
	float CurrentSpread;

	UPROPERTY(Transient, ReplicatedUsing = OnRep_HitNotify)
	FCGInstantHit HitNotify;

	/**The percentage of the clip fired by a single shot.*/
	UPROPERTY()
	float ClipPercentPerShot;

	////////////////////////////
	//  Components

	/** Used to manage the flash particle system. */
	UPROPERTY(Transient)
	UParticleSystemComponent* MuzzleFlashComp;

	UPROPERTY(Transient)
	UParticleSystemComponent* TrailPSC;

	/** Used to manage audio playback. */
	UPROPERTY(Transient)
	UAudioComponent* FireAudioComponent;

	/** Returns Mesh1P subobject **/
	FORCEINLINE USkeletalMeshComponent* GetMesh1P() const { return Mesh1P; };
	
	/** The ACGCharacter holding this weapon. Replication triggers the inventory update functions. */
	UPROPERTY(Transient, ReplicatedUsing = OnRep_CGOwner)
	ACGCharacter* CGOwner;

	UFUNCTION()
	void OnRep_CGOwner();


	////////////////////////////
	// State Functions 
#pragma region State Functions

	/** Invoked when a weapon enters the inventory of a player or bot. */
	void OnEnterInventory(class ACGCharacter* CGOwner);

	/** Invoked when a weapon exits the inventory of a player or bot. */
	void OnExitInventory();

	/** Invoked when the weapon is equipped by a player or bot. */
	virtual void OnEquip();

	/** Invoked when the weapon is unequipped by a player or bot. */
	virtual void OnUnequip();

	virtual void OnStartReload();
	
	UFUNCTION(server, reliable, WithValidation)
	void ServerStartReload();
	
	void StopReload();

	// TODO find a better way?
	/**Invoked by the server when a timer based call finishes execution.*/
	UFUNCTION(client, reliable)
	void ClientCheckQueuedInput();


	// This is managed by the weapon, not the state at the present.
	// FIXME
	virtual void StartOverheat();

	// Gives the Reload state the information it requires to spawn a timer.
	virtual float GetReloadTime() const;

	virtual bool CanReload() const;
		
	virtual void ApplyReload();



#pragma endregion

#pragma region Fire Functions

	/** Starts the firing of a weapon if possible. */
	virtual void StartFire();

	UFUNCTION(server, reliable, WithValidation)
	void ServerStartFire();

	/** Ends the firing of the weapon, stop in StartFire for non automatic weapons. */
	virtual void StopFire();

	UFUNCTION(server, reliable, WithValidation)
	void ServerStopFire();
	
	virtual bool StartFiring();

	virtual void StopFiring();

	virtual void StartWeaponFireSimulation();

	virtual void StopWeaponFireSimulation();

#pragma endregion

#pragma region Projectile

	void FireProjectile();

	UFUNCTION(server, reliable, WithValidation)
	void ServerFireProjectile(FVector Origin, FVector_NetQuantizeNormal ShootDir);

	virtual void SpawnProjectile(FVector Origin, FVector_NetQuantizeNormal ShootDir);

#pragma endregion

#pragma region Hit Scan

	virtual void FireHitScan();

	void ProcessHitScan(const FHitResult& Impact, const FVector& Origin, const FVector& ShootDir, int32 RandSeed, float Spread);
	
	virtual void ProcessHitScanConfirmed(const FHitResult& Impact, const FVector& Origin, const FVector& ShootDir, int32 RandSeed, float Spread);

	/** server notified of hit from client to verify */
	UFUNCTION(reliable, server, WithValidation)
	void ServerNotifyHit(const FHitResult Impact, FVector_NetQuantizeNormal ShootDir, int32 RandomSeed, float Spread);

	/** server notified of miss to show trail FX */
	UFUNCTION(unreliable, server, WithValidation)
	void ServerNotifyMiss(FVector_NetQuantizeNormal ShootDir, int32 RandomSeed, float Spread);

	UFUNCTION()
	void OnRep_HitNotify();

	void SimulateHitScan(const FVector& Origin, const FVector& ShotDir);

	virtual void SpawnTrailEffect(const FVector& EndPoint);

	// TODO
	void SpawnHitEffect(const FHitResult& Impact);

	bool ShouldDealDamage_Instant(AActor* TestActor) const;

	void DealDamage_Instant(const FHitResult& Impact, const FVector& ShootDir);

#pragma endregion

#pragma region Ammo

	virtual void UseAmmo();

	// If set to false it's a check by something like CGCharacter.
	virtual bool CanFire(bool InitFireCheck = false) const;

	virtual float GetClipPercent() const;

	float GetPercentPerShot() const { return ClipPercentPerShot; }

	virtual int32 GetAmmo() const { return 0; }


	virtual int32 GetAmmoInClip() const { return 0; }


#pragma endregion

	/**Replicates weapon fire simulation. */
	UFUNCTION()
	void OnRep_BurstCount();

	/**
	 * Sets the owner of the weapon. 
	 * @param The new owner of this weapon.	
	 */
	void SetCGOwner(ACGCharacter* NewOwner);

	/** Retrieves the owner of the weapon. */
	FORCEINLINE ACGCharacter* GetCGOwner() const {	return CGOwner;	}

	////////////////////////////
	// Weapon Transform Helpers

	/** Gets the aim vector for the player.*/
	FVector GetCameraAim() const;

	/** Gets the location of the player's camera.*/
	FVector GetCameraLocation() const;

	/** Gets the muzzle location for spawning projectiles and playing effects.*/
	FVector GetMuzzleLocation() const;

	/** Gets the vector for the rotation of the muzzle.*/
	FVector GetMuzzleRotation() const;

protected:
	FHitResult WeaponTrace(const FVector& TraceFrom, const FVector& TraceTo) const;


#pragma region Visuals

protected:
	/** Adds the mesh to the owner's mesh. */
	void AttachMeshToPawn();

	/** Removes the mesh from the owner's mesh. */
	void DetachMeshFromPawn();

#pragma endregion

#pragma region State Management
public :
	/**
	* Attempts to transition current state to the supplied state.
	*/
	void GotoState(UCGWeaponState* NewState);

	/**Switches the weapon to the equipping state.*/
	void GotoEquippingState();

	/**Switches the weapon to the firing state, Checks Ammo, Overheat, etc. May be overridem for this reason.*/
	virtual void GotoFiringState();

public:

	UPROPERTY(BlueprintReadOnly)
	UCGWeaponState* CurrentState;

protected:

	UPROPERTY(Instanced, EditAnywhere, BlueprintReadWrite, Category = "States")
	UCGWeaponState* ActiveState;

	UPROPERTY(Instanced, EditAnywhere, BlueprintReadWrite, Category = States)
	UCGWeaponState* InactiveState;

	UPROPERTY(Instanced, EditAnywhere, BlueprintReadWrite, Category = States)
	UCGWeaponState* EquippingState;

	UPROPERTY(Instanced, EditAnywhere, BlueprintReadWrite, Category = States)
	UCGWeaponState* UnequippingState;

	UPROPERTY(Instanced, EditAnywhere, BlueprintReadWrite, Category = States)
	UCGWeaponState* ReloadingState;
	
	UPROPERTY(Instanced, EditAnywhere, BlueprintReadWrite, Category = States)
	UCGWeaponState* FiringState;

#pragma endregion

};
