// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "Weapons/CrystallineWeapon.h"
#include "CrystallinePistol.generated.h"

USTRUCT()
struct FPistolProjectileData
{
	GENERATED_USTRUCT_BODY()

	/** The maximum "heat" that the pistol can achieve before */
	UPROPERTY(EditDefaultsOnly)
	float MaxHeat;

	/** The heat generated by each shot. */
	UPROPERTY(EditDefaultsOnly)
	float HeatPerShot;

	/** Heat reduction per second.*/
	UPROPERTY(EditDefaultsOnly)
	float CooldownPerSecond;

	/** The amount of time that the weapon is in the "overheat" state. */
	UPROPERTY(EditDefaultsOnly)
	float OverheatTime;

	/** Sets defaults */
	FPistolProjectileData()
	{
		// Heat settings.
		MaxHeat = 100.f;
		HeatPerShot = 15.f;
		CooldownPerSecond = 30.f;
		OverheatTime = 0.5f;
	}

};

/**
 * A cooldown based projectile weapon.
 */
UCLASS(Abstract)
class CRYSTALLINE_API ACrystallinePistol : public ACrystallineWeapon
{
	GENERATED_UCLASS_BODY()

	/** The configuration for the pistol's projectile. */
	UPROPERTY(EditDefaultsOnly, Category = Config)
	FProjectileData ProjectileConfig;

	UPROPERTY(EditDefaultsOnly, Category = Config)
	FPistolProjectileData PistolConfig;

	//TODO this may need some degree of networking.	
	/** Identifies if the pistol is in the overheated state, no shots are allowed. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = State)
	uint32 bIsOverheated : 1;

	/** Identifies if the pistol is in the overheated state, no shots are allowed. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = State)
	uint32 bIsCoolingDown : 1;

	////////////////////////////////////
	// Overheat Mechanic
	/** The current heat of the weapon, Zero at start.*/
	UPROPERTY(Transient)
	float WeaponHeat;

	/** Updates the weapon on tick. Used for the heat mechanic.*/
	virtual void Tick(float DeltaSeconds) override;

	virtual float GetClipPercent() const override;

protected:

	/** Fires the pistol projectile. */
	virtual void FireWeapon() override;
	
	virtual void UseAmmo() override;
	
	virtual bool CanFire() override;

	/** Fires a projectile on the server. */
	UFUNCTION(reliable, server, WithValidation)
	void ServerFireProjectile(FVector Origin, FVector_NetQuantizeNormal ShootDir);

	

	/////////////////////////////////////
	// Overheat Mechanic
	void HandleOverheatCooldown();

	void FinishCooldown();

	
};
